### ISSUE TITLE
Typing

### ISSUE THREAD

**Issue by MarkGotham** [music-computing/amads#47]
Preference for `Union[float, int]` over `Number`?

**Comment by MarkGotham** [comment]
Don't think this is explicit in dev notes for `Types` the `developer_notes/style.rst`

**Comment by pmcharrison** [comment]
Good question! The disadvantage with Number is that technically it includes complex numbers. My understanding is that the best thing to do here is use `float`, as for the purpose of type checking `int` is considered a special case of `float`, so you don't need the `Union`.

**Comment by MarkGotham** [comment]
Great, thanks. float it is!

And, on reflection, probably too niche for the dev docs ;)
